### ISSUE TITLE
isb-cgc-pipelines-startup.sh no longer hosted on gs

### ISSUE THREAD

**Issue by tjl3** [isb-cgc/ISB-CGC-pipelines#10]
Hello. I was wondering where one might access the startup script gs://isb-cgc-open/vm-startup-scripts/isb-cgc-pipelines-startup.sh (mentioned in the README.md) It appears to no longer be hosted at that location. Is it the same script as the instance-startup.sh script in the repo?

**Comment by smrgit** [comment]
Thank you for letting us know about this.  The startup script is now located in 
```
gs://isb-cgc-misc/compute-helpers/vm-startup-scripts/isb-cgc-pipelines-startup.sh
```
I will update the documentation.

**Comment by tjl3** [comment]
Thanks!
