### ISSUE TITLE
Restarting Jobs

### ISSUE THREAD

**Issue by pjtatlow** [isb-cgc/ISB-CGC-pipelines#4]
In the README it says all you have to run is `isb-cgc-pipelines restart <jobId>` to restart a job, but this didn't work for me. I did not receive an error, and it exited like it succeeded, but the job didn't restart. I had to do `isb-cgc-pipelines restart --jobId <jobId>` to get it to work. Only then did it lose it's FAILED status and start up again.

**Comment by vardaofthevalier** [comment]
I just updated the README to reflect that the "--jobId" flag is required for the command to function properly.  Thanks for pointing that out!
