### ISSUE TITLE
What is a "pipeline"?  

### ISSUE THREAD

**Issue by seandavi** [isb-cgc/ISB-CGC-pipelines#5]
It would help people new to cloud computing and, in particular, ISB-CGC, to get a high-level description of what a pipeline is.  Some background and a high-level overview would greatly enhance the onboarding of users.

**Comment by vardaofthevalier** [comment]
Hi there, just wanted to let you know that I recently added a "Terminology Clarification" section to help with understanding what is meant by "pipeline" in this context.  I'm still in the process of working on more thorough documentation, so I will leave this open until I have a chance to provide a more comprehensive update.  Thanks for the feedback!
